In [96]:
import pandas as pd

# lgb

In [27]:
# 三天50ｗ融合
lgb_result = pd.read_csv('lgb-0.964666.csv')
sub1 = pd.DataFrame()
sub1['probability'] = lgb_result['probability']

In [97]:
# 单天最高
lgb_result = pd.read_csv('75w-0.964869.csv')
sub1 = pd.DataFrame()
sub1['probability'] = lgb_result['probability']

# xgb

In [98]:
xgb_result = pd.read_csv('xgb-0.964106.csv')
sub2 = pd.DataFrame()
sub2['probability'] = xgb_result['probability']

# xDeepFM

In [99]:
xDeepFM_result = pd.read_csv('xdeepfm_0.958468.csv')
sub3 = pd.DataFrame()
sub3['probability'] = xDeepFM_result['probability']

# 融合(权重需要试)

# 0.4-0.4-0.2   score:0.963799

In [14]:
sub = pd.DataFrame({'id':lgb_result['id']})
sub['probability'] = (0.4*sub1['probability'] + 
                      0.4*sub2['probability'] + 
                      0.2*sub3['probability']).round(6)

sub.to_csv('submission_0.4_0.4_0.2.csv',index = False)

# 加权平均   score:0.963176

In [20]:
sub = pd.DataFrame({'id':lgb_result['id']})
sub['probability'] = (sub1['probability'] + 
                      sub2['probability'] + 
                      sub3['probability'])/3
sub['probability'] = sub['probability'].round(6)

sub.to_csv('submission_0.33_0.33_0.33.csv',index = False)

# 0.964886 和其他

In [95]:
sub = pd.DataFrame({'id':lgb_result['id']})
sub['probability'] = (0.6*sub1['probability'] + 
                      0.3*sub2['probability'] + 
                      0.1*sub3['probability']).round(6)

sub.to_csv('submission_0.6_0.3_0.1.csv',index = False)

# 投票

In [100]:
sub = pd.DataFrame({'id':lgb_result['id']})
sub['probability1'] = lgb_result['probability']
sub['probability2'] = xgb_result['probability']
sub['probability3'] = xDeepFM_result['probability']
sub.head(20)

    id  probability1  probability2  probability3
0    1      0.264105      0.274712      0.260011
1    2      0.999833      0.987583      0.999875
2    3      0.999869      0.988076      0.999982
3    4      0.079545      0.106634      0.092703
4    5      0.999879      0.987948      0.999974
5    6      0.292116      0.283548      0.291113
6    7      0.022498      0.027105      0.015347
7    8      0.999826      0.987802      0.999945
8    9      0.018550      0.028457      0.013198
9   10      0.137616      0.175595      0.160349
10  11      0.999868      0.987915      0.999974
11  12      0.999886      0.987999      0.999984
12  13      0.549756      0.543992      0.617490
13  14      0.205971      0.198609      0.169891
14  15      0.999907      0.987988      0.999958
15  16      0.061762      0.107813      0.250900
16  17      0.165702      0.172375      0.137638
17  18      0.647380      0.611825      0.679934
18  19      0.150971      0.161827      0.156308
19  20      0.081142      0.111548      0.520366

In [101]:
cols = ['probability1','probability2','probability3']

In [102]:
sub[sub[cols] < 0.5] = 0
sub[sub[cols] >= 0.5] = 1

In [103]:
sub.head(20)

    id  probability1  probability2  probability3
0    1           0.0           0.0           0.0
1    2           1.0           1.0           1.0
2    3           1.0           1.0           1.0
3    4           0.0           0.0           0.0
4    5           1.0           1.0           1.0
5    6           0.0           0.0           0.0
6    7           0.0           0.0           0.0
7    8           1.0           1.0           1.0
8    9           0.0           0.0           0.0
9   10           0.0           0.0           0.0
10  11           1.0           1.0           1.0
11  12           1.0           1.0           1.0
12  13           1.0           1.0           1.0
13  14           0.0           0.0           0.0
14  15           1.0           1.0           1.0
15  16           0.0           0.0           0.0
16  17           0.0           0.0           0.0
17  18           1.0           1.0           1.0
18  19           0.0           0.0           0.0
19  20           0.0           0.0           1.0

In [104]:
sub['count'] = sub[cols].sum(axis = 1)

In [105]:
sub.head(20)

    id  probability1  probability2  probability3  count
0    1           0.0           0.0           0.0    0.0
1    2           1.0           1.0           1.0    3.0
2    3           1.0           1.0           1.0    3.0
3    4           0.0           0.0           0.0    0.0
4    5           1.0           1.0           1.0    3.0
5    6           0.0           0.0           0.0    0.0
6    7           0.0           0.0           0.0    0.0
7    8           1.0           1.0           1.0    3.0
8    9           0.0           0.0           0.0    0.0
9   10           0.0           0.0           0.0    0.0
10  11           1.0           1.0           1.0    3.0
11  12           1.0           1.0           1.0    3.0
12  13           1.0           1.0           1.0    3.0
13  14           0.0           0.0           0.0    0.0
14  15           1.0           1.0           1.0    3.0
15  16           0.0           0.0           0.0    0.0
16  17           0.0           0.0           0.0    0.0
17  18           1.0           1.0           1.0    3.0
18  19           0.0           0.0           0.0    0.0
19  20           0.0           0.0           1.0    1.0

In [106]:
sub.loc[sub['count'] >= 2,'label'] = 1
sub.loc[sub['count'] < 2,'label'] = 0

In [107]:
sub.head(20)

    id  probability1  probability2  probability3  count  label
0    1           0.0           0.0           0.0    0.0    0.0
1    2           1.0           1.0           1.0    3.0    1.0
2    3           1.0           1.0           1.0    3.0    1.0
3    4           0.0           0.0           0.0    0.0    0.0
4    5           1.0           1.0           1.0    3.0    1.0
5    6           0.0           0.0           0.0    0.0    0.0
6    7           0.0           0.0           0.0    0.0    0.0
7    8           1.0           1.0           1.0    3.0    1.0
8    9           0.0           0.0           0.0    0.0    0.0
9   10           0.0           0.0           0.0    0.0    0.0
10  11           1.0           1.0           1.0    3.0    1.0
11  12           1.0           1.0           1.0    3.0    1.0
12  13           1.0           1.0           1.0    3.0    1.0
13  14           0.0           0.0           0.0    0.0    0.0
14  15           1.0           1.0           1.0    3.0    1.0
15  16           0.0           0.0           0.0    0.0    0.0
16  17           0.0           0.0           0.0    0.0    0.0
17  18           1.0           1.0           1.0    3.0    1.0
18  19           0.0           0.0           0.0    0.0    0.0
19  20           0.0           0.0           1.0    1.0    0.0

In [108]:
sub['probability1'] = lgb_result['probability']
sub['probability2'] = xgb_result['probability']
sub['probability3'] = xDeepFM_result['probability']

In [109]:
sub.head(20)

    id  probability1  probability2  probability3  count  label
0    1      0.264105      0.274712      0.260011    0.0    0.0
1    2      0.999833      0.987583      0.999875    3.0    1.0
2    3      0.999869      0.988076      0.999982    3.0    1.0
3    4      0.079545      0.106634      0.092703    0.0    0.0
4    5      0.999879      0.987948      0.999974    3.0    1.0
5    6      0.292116      0.283548      0.291113    0.0    0.0
6    7      0.022498      0.027105      0.015347    0.0    0.0
7    8      0.999826      0.987802      0.999945    3.0    1.0
8    9      0.018550      0.028457      0.013198    0.0    0.0
9   10      0.137616      0.175595      0.160349    0.0    0.0
10  11      0.999868      0.987915      0.999974    3.0    1.0
11  12      0.999886      0.987999      0.999984    3.0    1.0
12  13      0.549756      0.543992      0.617490    3.0    1.0
13  14      0.205971      0.198609      0.169891    0.0    0.0
14  15      0.999907      0.987988      0.999958    3.0    1.0
15  16      0.061762      0.107813      0.250900    0.0    0.0
16  17      0.165702      0.172375      0.137638    0.0    0.0
17  18      0.647380      0.611825      0.679934    3.0    1.0
18  19      0.150971      0.161827      0.156308    0.0    0.0
19  20      0.081142      0.111548      0.520366    1.0    0.0

In [110]:
sub.loc[sub['label'] == 1,'probability'] = sub[cols].max(axis = 1)
sub.loc[sub['label']== 0,'probability'] = sub[cols].min(axis = 1)

In [111]:
sub.head(50)

    id  probability1  probability2  probability3  count  label  probability
0    1      0.264105      0.274712      0.260011    0.0    0.0     0.260011
1    2      0.999833      0.987583      0.999875    3.0    1.0     0.999875
2    3      0.999869      0.988076      0.999982    3.0    1.0     0.999982
3    4      0.079545      0.106634      0.092703    0.0    0.0     0.079545
4    5      0.999879      0.987948      0.999974    3.0    1.0     0.999974
5    6      0.292116      0.283548      0.291113    0.0    0.0     0.283548
6    7      0.022498      0.027105      0.015347    0.0    0.0     0.015347
7    8      0.999826      0.987802      0.999945    3.0    1.0     0.999945
8    9      0.018550      0.028457      0.013198    0.0    0.0     0.013198
9   10      0.137616      0.175595      0.160349    0.0    0.0     0.137616
10  11      0.999868      0.987915      0.999974    3.0    1.0     0.999974
11  12      0.999886      0.987999      0.999984    3.0    1.0     0.999984
12  13      0.549756      0.543992      0.617490    3.0    1.0     0.617490
13  14      0.205971      0.198609      0.169891    0.0    0.0     0.169891
14  15      0.999907      0.987988      0.999958    3.0    1.0     0.999958
15  16      0.061762      0.107813      0.250900    0.0    0.0     0.061762
16  17      0.165702      0.172375      0.137638    0.0    0.0     0.137638
17  18      0.647380      0.611825      0.679934    3.0    1.0     0.679934
18  19      0.150971      0.161827      0.156308    0.0    0.0     0.150971
19  20      0.081142      0.111548      0.520366    1.0    0.0     0.081142
20  21      0.019399      0.025113      0.010304    0.0    0.0     0.010304
21  22      0.215349      0.236798      0.227514    0.0    0.0     0.215349
22  23      0.999865      0.988001      0.999985    3.0    1.0     0.999985
23  24      0.999870      0.987886      0.999982    3.0    1.0     0.999982
24  25      0.372140      0.324632      0.343676    0.0    0.0     0.324632
25  26      0.118570      0.108225      0.114743    0.0    0.0     0.108225
26  27      0.999869      0.987934      0.999984    3.0    1.0     0.999984
27  28      0.999899      0.988158      0.999971    3.0    1.0     0.999971
28  29      0.123828      0.162514      0.166640    0.0    0.0     0.123828
29  30      0.568923      0.534677      0.575710    3.0    1.0     0.575710
30  31      0.999869      0.988023      0.999975    3.0    1.0     0.999975
31  32      0.111139      0.091687      0.107045    0.0    0.0     0.091687
32  33      0.501142      0.460247      0.477631    1.0    0.0     0.460247
33  34      0.533967      0.540001      0.497403    2.0    1.0     0.540001
34  35      0.037771      0.027115      0.031014    0.0    0.0     0.027115
35  36      0.191988      0.209158      0.210106    0.0    0.0     0.191988
36  37      0.322480      0.385279      0.358872    0.0    0.0     0.322480
37  38      0.155756      0.164663      0.115905    0.0    0.0     0.115905
38  39      0.999870      0.987906      0.999978    3.0    1.0     0.999978
39  40      0.188458      0.202174      0.188208    0.0    0.0     0.188208
40  41      0.044887      0.089047      0.317945    0.0    0.0     0.044887
41  42      0.999856      0.987906      0.999893    3.0    1.0     0.999893
42  43      0.030815      0.030515      0.033375    0.0    0.0     0.030515
43  44      0.126225      0.127816      0.102180    0.0    0.0     0.102180
44  45      0.999853      0.988048      0.999903    3.0    1.0     0.999903
45  46      0.587328      0.575431      0.599157    3.0    1.0     0.599157
46  47      0.539581      0.545745      0.578692    3.0    1.0     0.578692
47  48      0.999874      0.988196      0.999986    3.0    1.0     0.999986
48  49      0.057006      0.086729      0.032659    0.0    0.0     0.032659
49  50      0.270784      0.299331      0.309703    0.0    0.0     0.270784

In [112]:
submission = pd.DataFrame({'id':sub['id'],'probability':sub['probability']})

In [113]:
submission['probability']=submission['probability'].round(6)

In [114]:
submission.to_csv('submission_vote_2.csv',index = False)

In [115]:
submission.head(10)

   id  probability
0   1     0.260011
1   2     0.999875
2   3     0.999982
3   4     0.079545
4   5     0.999974
5   6     0.283548
6   7     0.015347
7   8     0.999945
8   9     0.013198
9  10     0.137616